## Setup 1

In [1]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] #np.array(a) till then it is list

In [2]:
sum_of_a = sum(a) #why not a.sum()? # a.sum() would work if it was an array
print(sum_of_a)

55


In [3]:
min_of_a = min(a)
print(min_of_a)

1


In [4]:
max_of_a = max(a) 
print(max_of_a)

10


In [5]:
mean_of_a = sum(a)/len(a) #built in python method

In [6]:
import statistics #an import method

In [7]:
mean_of_a = statistics.mean(a)

In [8]:
def product_of_a(alist):
    q = 1
    for x in alist:
        q *=x
    return q
product_of_a(a)

3628800

In [9]:
# !! not gonna work: squares_of_a = a ** 2 #need for loop or comprehension for list (append)

# sqr = lambda x: x * x
# sqr(a)
# TypeError: can't multiply sequence by non-int of type 'list'

sqr_list = [x**2 for x in a]
sqr_list

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [10]:
import numpy as np #for comparison

In [11]:
np.power(a, 2)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [12]:
odds_in_a = [x for x in a if x % 2 != 0]
odds_in_a

[1, 3, 5, 7, 9]

In [13]:
evens_in_a = [x for x in a if x % 2 == 0] 
# note that a % 2 == 0 wont work cuz its a list, 
# so you need a loop to hit each element in the list (but numpy could do it, it's designed for vector operations)
# TypeError: unsupported operand type(s) for %: 'list' and 'int'

## Setup 2

In [14]:
c = [
    [3, 4, 5],
    [6, 7, 8]
]

In [15]:
b = np.array(c)
print(b)

[[3 4 5]
 [6 7 8]]


In [16]:
b.sum()

33

In [17]:
b.min()

3

In [18]:
b.max()

8

In [19]:
b.mean()

5.5

In [20]:
b**2

array([[ 9, 16, 25],
       [36, 49, 64]])

In [27]:
b % 2 != 0

array([[ True, False,  True],
       [False,  True, False]])

In [28]:
b[b% 2 !=0]

array([3, 5, 7])

In [30]:
b % 2 == 0

array([[False,  True, False],
       [ True, False,  True]])

In [31]:
b[b% 2 ==0]

array([4, 6, 8])

In [32]:
b.shape

(2, 3)

In [33]:
b.transpose

<function ndarray.transpose>

In [34]:
np.transpose(b)

array([[3, 6],
       [4, 7],
       [5, 8]])

In [37]:
np.reshape(b, (1,6))

array([[3, 4, 5, 6, 7, 8]])

In [38]:
np.reshape(b, (6,1))

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [40]:
t =[
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [41]:
c = np.array(t)

In [42]:
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [43]:
np.std(c)

2.581988897471611

In [47]:
np.var(c)

6.666666666666667

In [46]:
print(c.shape)

(3, 3)


In [45]:
print(np.transpose(c))

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [49]:
np.dot(c,c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [54]:
np.sum(c* np.transpose(c))

261

In [55]:
c*np.transpose(c) #!!!!!!!!!!!!!# wrong answer

array([[ 1,  8, 21],
       [ 8, 25, 48],
       [21, 48, 81]])

In [56]:
d = np.array([
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
])

In [57]:
d

array([[ 90,  30,  45,   0, 120, 180],
       [ 45, -90, -30, 270,  90,   0],
       [ 60,  45, -45,  90, -45, 180]])

In [58]:
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

In [59]:
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

In [60]:
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

In [61]:
d[d<0]

array([-90, -30, -45, -45])

In [62]:
d[d>0]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

In [64]:
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

In [65]:
d.shape

(3, 6)

In [68]:
np.shape(np.transpose(d))

(6, 3)

In [70]:
np.reshape(d, (9, 2))

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])